Develop
PrudnikovV/codebreacker pull request #1
Opened 2022-07-31 08:54 UTC by PrudnikovV

2022-08-03 22:18 UTC, kolyanjy requested changes

2022-08-03 22:18 UTC, kolyanjy commented on .circleci/config.yml
> +      - image: cimg/ruby:3.1-browsers
I think we don't need browsers in image

2022-08-03 22:18 UTC, kolyanjy commented on .circleci/config.yml
> +            - lintering
add empty line

2022-08-03 22:18 UTC, kolyanjy commented on .gitignore
> +test_spec.yml
what is that?

2022-08-03 22:18 UTC, kolyanjy commented on .overcommit.yml
> +
Good thing 👍 
also you can take a look on this [one](https://github.com/evilmartians/lefthook)

2022-08-03 22:18 UTC, kolyanjy commented on lib/attempt.rb
> +    def colculation
tipo: calculation

2022-08-03 22:18 UTC, kolyanjy commented on lib/attempt.rb
> +      @result += ["-"] * (@attempt_code.uniq.map { |e| min_quentyty(e) }.sum - result.count)
move '+' and '-' to constants

2022-08-03 22:18 UTC, kolyanjy commented on lib/attempt.rb
> +    def min_quentyty(elm)
tipo: min_quantity

2022-08-03 22:18 UTC, kolyanjy commented on lib/codebreaker.rb
> +  class Error < StandardError; end
move to separate file and use more correct naming

2022-08-03 22:18 UTC, kolyanjy commented on lib/difficulty.rb
> +
I think here must be suite with hints and attempts quantity

2022-08-03 22:18 UTC, kolyanjy commented on lib/winner.rb
> +  end
i think this class redundant. we can just save user which win game

2022-08-03 22:18 UTC, kolyanjy commented on lib/game.rb
> +      Array.new(4) { rand(1..6) }
Pls move range to constant

2022-08-03 22:18 UTC, kolyanjy commented on spec/game_spec.rb
> +  let(:difficulty) { Codebreaker::Difficulty.new("Easy", 15, 2) }
you just need to provide name of difficulty. quantity of attempts and hints must be resolved in difficulty class

2022-08-03 22:18 UTC, kolyanjy commented on lib/difficulty.rb
> +    def initialize(name, attempts, hints)
just name

2022-08-04 06:42 UTC, PrudnikovV commented on .gitignore
> +test_spec.yml
This was by default, after "bundle gem codebraker"

2022-08-09 15:13 UTC, kolyanjy approved these changes
Fix comments and merge

2022-08-09 15:13 UTC, kolyanjy commented on .circleci/config.yml
> +
pls add rule with last empty line to rubocop for avoid it
<img width="117" alt="image" src="https://user-images.githubusercontent.com/26035028/183687360-913dec26-cac6-4394-ab3b-88a897b95b6d.png">

2022-08-09 15:13 UTC, kolyanjy commented on lib/codebreaker.rb
> +  class Error < StandardError; end
Still not resolved.

2022-08-09 15:13 UTC, kolyanjy commented on lib/difficulty.rb
> +    STANDART_DIFFICULTIES =
👍

2022-08-19 06:46 UTC, merged